# Where things are
source: ./src
destination: ./slides
layouts_dir: _layouts
data_dir: _includes

# Handling Reading
exclude:      [
  'fonts',
  'img',
  'js',
  'scss'
]
keep_files: [
  'css',
  'img',
  'fonts',
  'js'
]
encoding: 'utf-8'

